### ISSUE TITLE
telnet: Unable to connect to remote host: Connection refused

### ISSUE THREAD

**Issue by Yo-yo-ooo** [Minep/lunaix-os#12] opened 2022-12-27 06:27 UTC
如题

**Comment by Minep** [comment] 2022-12-29 21:30
Could you please elaborate your issue here? For example, how you encounter this, what have you already observed when this error pops up. It would be a good habit to cultivate especially you are posting any issue.

From the title, I can only guess that you are executing things like `make debug-qemu`. If that is the case, it will start a new terminal session and attach to qemu's monitor via telnet. So the cause could be your qemu is misbehaving. Could you confirm that you have install qemu properly?

It would be much easier for me to locate potential cause if you are willing to provide more detailed descriptions on the issue here. Thank you.

**Comment by Yo-yo-ooo** [comment] 2023-01-21 05:36
我在运行make run时告诉我的错误

**Comment by Yo-yo-ooo** [comment] 2023-01-21 06:34
![image](https://user-images.githubusercontent.com/98507772/213847118-4dc9db17-3e82-4a21-85c7-c2483c18800d.png)

**Comment by Minep** [comment] 2023-01-25 10:06
Could you verify your qemu installation and the version by executing `qemu-i386 --version`. This issues is pretty unusual, furthermore, could you tell me the commit that your HEAD are currently points to?

**Comment by Yo-yo-ooo** [comment] 2023-01-27 06:58
用的是最新的 commit HEAD qemu版本也是最新的

**Comment by Minep** [comment] 2023-10-08 15:00
Due to a long-term silence of this thread, I am closing it down. You are welcome to reopen it if you have any further update.

**Closed by Minep** 2023-10-08 15:00 UTC
Labels: help wanted
