### ISSUE TITLE
Error: unsupported instruction `mov' when running "make all"

### ISSUE THREAD

**Issue by Tgist1024** [Minep/lunaix-os#6] opened 2022-10-14 20:15 UTC
Full Error Message
--------------------
```shell
$ make all    
 BUILD: arch/x86/boot.S
arch/x86/boot.S: Assembler messages:
arch/x86/boot.S:78: Error: unsupported instruction `mov'
arch/x86/boot.S:80: Error: unsupported instruction `mov'
arch/x86/boot.S:84: Error: unsupported instruction `mov'
arch/x86/boot.S:86: Error: unsupported instruction `mov'
arch/x86/boot.S:88: Error: unsupported instruction `mov'
arch/x86/boot.S:94: Error: invalid instruction suffix for `push'
make: *** [makefile:24: build/obj/arch/x86/boot.S.o] Error 1
```
gcc,binutils Version
---------------------
```shell
$ i686-elf-gcc -dumpmachine
i686-elf
$ i686-elf-gcc --version
i686-elf-gcc (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ i686-elf-as --version
GNU assembler (GNU Binutils) 2.39
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `i686-elf'.
```
System Info
---------------
```shell
OS: Arch Linux x86_64 
Host: HP EliteBook 840 G3 
Kernel: 6.0.1-arch2-1 
Uptime: 8 hours, 9 mins 
Packages: 1123 (pacman) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: Plasma 5.26.0 
WM: KWin 
Terminal: yakuake 
CPU: Intel i5-6200U (4) @ 2.800GHz 
GPU: Intel Skylake GT2 [HD Graphics 520] 
Memory: 4298MiB / 15883MiB 
```
我猜测是binutils-2.39不再支持类似的指令了？请问我需要改用低版本的gcc和binutils吗？

**Comment by Minep** [comment] 2022-10-22 00:40
Commonly speaking, this behaviour is usually caused by trying to compile a 32-bits asm code using 64-bits gcc. However, this surely contradicts your configuration.

My rough guess is there could be some alteration in the compiling process of gcc v12.2, perhaps, some switches/flags need to be flipped...? which will be investigated further.

And... yes, it is worth to try downgrade your toolchain. (Mine is gcc v11.2, as v2.37)

Should the issue remains, please let me know! Meanwhile, I will start investigating this issue and get you an update if any progress.

**Comment by Minep** [comment] 2022-10-22 22:19
Ok... I have setup a toolchain as per your config. And unfortunately, I could not reproduce your issue.

However, there is an theoretically useless fix: Append a "-m32" flag to the $CFLAGS located in config/make-cc and see if the problem remains. This will force gdb to use 32bits ABI to compile your code. 

Although, I believe it is unlikely to work as your gdb is already configured to i686 (hence "theoretically useless"), but it is worth to give a shot.

If that does not work as well. Then, you can post the boot.S source file so I can make sure that we are on the same page (i.e. you are compile the latest commit).

**Comment by Tgist1024** [comment] 2022-10-23 11:29
> Commonly speaking, this behaviour is usually caused by trying to compile a 32-bits asm code using 64-bits gcc. However, this surely contradicts your configuration.
> 
> My rough guess is there could be some alteration in the compiling process of gcc v12.2, perhaps, some switches/flags need to be flipped...? which will be investigated further.
> 
> And... yes, it is worth to try downgrade your toolchain. (Mine is gcc v11.2, as v2.37)
> 
> Should the issue remains, please let me know! Meanwhile, I will start investigating this issue and get you an update if any progress.

Acctually after reinstalling gcc and binutils like the gcc-build.sh you provided, it just works.
I think all these errors are because I have gcc and binutils installed in two different directories, while they should be in the same place.**My fault!**😂

**Closed** 2022-10-23 11:31 UTC
Labels: bug, compiler
